Use vite & Config API endpoint URL

diff --git a/Dockerfile.frontend b/Dockerfile.frontend
--- a/Dockerfile.frontend
+++ b/Dockerfile.frontend
@@ -1,19 +1,29 @@
 # Start from a Node image
-FROM node:14
+FROM node:18-alpine AS base
 
-# Set the working directory
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Copy over the react files and package.json
-COPY ./src /app/src
-COPY ./public /app/public
-COPY ./package.json /app
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Install the node dependencies
-RUN npm install
 
-# Expose the port for the server
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
 EXPOSE 3000
 
-# Start the server
-CMD ["npm", "start"]
+# 配置 Vite 服务器
+CMD ["yarn", "dev"]
